_id: prodromou-prodromos
_sources:
- http://www.parliament.cy/easyconsole.cfm/id/259
- http://www.parliament.cy/easyconsole.cfm/id/400
- http://www.parliament.cy/easyconsole.cfm/id/2016
birth_date: '1958-11-23'
contact_details:
- note: parliament
  type: address
  value: Βουλή των Αντιπροσώπων, 1402 Λευκωσία
- type: email
  value: ppmail@cytanet.com.cy
- note: parliament
  type: email
  value: pprodromou@parliament.cy
- type: fax
  value: (+357) 22 375800
- note: parliament
  type: voice
  value: (+357) 22 407232
dofi: null
email: pprodromou@parliament.cy
gender: male
identifiers:
- identifier: null
  scheme: http://www.wikidata.org/entity/
image: http://www.parliament.cy/assets/image/imageoriginal/PRODROMOU Prodromos.jpg
images:
- http://www.parliament.cy/assets/image/imageoriginal/PRODROMOU Prodromos.jpg
links:
- note:
    el: Προφίλ στην ιστοσελίδα της Βουλής
    en: Page on Parliament website
    tr: Parlemento websitesindeki sayfa
  url: http://www.parliament.cy/easyconsole.cfm/id/400
- note:
    el: Προσωπική ιστοσελίδα
    en: Personal website
    tr: Kişisel websitesi
  url: http://pprodromou.net/
- note:
    el: twitter
    en: twitter
    tr: twitter
  url: https://twitter.com/pprodromou
name:
  el: Προδρόμου Πρόδρομος
  en: Prodromou Prodromos
  tr: Prodrómu Pródromos
other_names:
- name: Prodromou Prodromos
  note: Official spelling in the 'en' locale; possibly anglicised
- name: Prodromou Prodromos
  note: Official spelling in the 'en' locale; possibly anglicised
tenures:
- electoral_district_id: lefkosia
  end_date: '2004-05-01'
  parliamentary_period_id: '8'
  party_id: disy
- electoral_district_id: lefkosia
  parliamentary_period_id: '8'
  party_id: null
  start_date: '2004-05-02'
- electoral_district_id: lefkosia
  parliamentary_period_id: '10'
  party_id: disy
  start_date: '2013-03-07'
